# Generated by Django 4.1.4 on 2022-12-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TituloBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtitulo', models.CharField(max_length=4)),
                ('titulo', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('pagocuota', models.CharField(max_length=1)),
            ],
        ),
    ]
