# Generated by Django 4.1.4 on 2022-12-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulo_bancario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulobancario',
            options={'verbose_name': 'Titulo Bancario', 'verbose_name_plural': 'Titulos Bancarios'},
        ),
    ]
