# Generated by Django 4.1.4 on 2022-12-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulo_bancario', '0002_alter_titulobancario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulobancario',
            options={},
        ),
        migrations.AlterModelTable(
            name='titulobancario',
            table='titulo_bancario',
        ),
    ]
